name: Book Setup
description: Install mdBook dependencies and levarage caching.
runs:
  using: composite
  steps:
  - name: Build setup
    uses: ./.github/actions/build_setup
  - name: mdBook setup
    uses: peaceiris/actions-mdbook@v2
    with:
      mdbook-version: 'latest'
  - name: Install `mdbook-cmdrun`
    uses: taiki-e/cache-cargo-install-action@v3
    with:
      tool: mdbook-cmdrun
      # TEMP: https://github.com/FauconFan/mdbook-cmdrun/pull/23
      git: https://github.com/roberth/mdbook-cmdrun
      rev: 3947c797d063352e0f983311c078430215cc1cca
